import { Burger } from "../types/BurgerType";

export const burgersData: Burger[] = [
  { 
    id: 1,
    type: "Cheeseburger",
    name: "Wendy's Burger",
    icon: require("../assets/icons/burgers-images/wendys-burger.png"),
    rating: 4.4,
    description: "The Cheeseburger Wendy's Burger is a classic fast food burger that packs a punch of flavor in every bite. Made with a juicy beef patty cooked to perfection, it's topped with melted American cheese, crispy lettuce, ripe tomato, and crunchy pickles.",
    cookingTime: 26,
    price: 8.24,
    category: "Classic",
  },
  { 
    id: 2,
    type: "Hamburger",
    name: "Veggie Burger",
    icon: require("../assets/icons/burgers-images/veggie-burger.png"),
    rating: 4.5,
    description: "Enjoy our delicious Hamburger Veggie Burger, made with a savory blend of fresh vegetables and herbs, topped with crisp lettuce, juicy tomatoes, and tangy pickles, all served on a soft, toasted bun.",
    cookingTime: 14,
    price: 9.99,
    category: "Sliders",
  },
  { 
    id: 3,
    type: "Hamburger",
    name: "Chicken Burger",
    icon: require("../assets/icons/burgers-images/hamburger-chicken-burger.png"),
    rating: 4.7,
    description: "Our chicken burger is a delicious and healthier alternative to traditional beef burgers, perfect for those looking for a lighter meal option. Try it today and experience the mouth-watering flavors of our Hamburger Chicken Burger!",
    cookingTime: 42,
    price: 12.48,
    category: "Combos",
  },
  { 
    id: 4,
    type: "Hamburger",
    name: "Fried Chicken Burger",
    icon: require("../assets/icons/burgers-images/fried-chicken-burger.png"),
    rating: 4.6,
    description: "Indulge in our crispy and savory Fried Chicken Burger, made with a juicy chicken patty, hand-breaded and deep-fried to perfection, served on a warm bun with lettuce, tomato, and a creamy sauce.",
    cookingTime: 14,
    price: 17.99,
    category: "Classic",
  },
  {
    id: 5,
    type: "Hamburger",
    name: "Beef Burger",
    icon: require("../assets/icons/burgers-images/hamburger-beef-burger.png"),
    rating: 4.9,
    description: "Treat yourself to a juicy, perfectly grilled beef patty on a toasted bun, topped with crisp lettuce, fresh tomato, melted cheddar, and smoky sauce. A classic burger packed with flavor in every bite.",
    cookingTime: 15,
    price: 24.99,
    category: "Classic",
  },
  {
    id: 6,
    type: "Burger",
    name: "Black Angus Burger",
    icon: require("../assets/icons/burgers-images/black-angus-burger.png"),
    rating: 4.8,
    description: "Indulge in a tender Black Angus beef patty on a brioche bun, topped with fresh onions, aged cheddar, lettuce, and tangy sauce for a rich, gourmet experience.",
    cookingTime: 17,
    price: 22.99,
    category: "Sliders",
  },
];
